# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deploy:
    docker:
       - image: circleci/node:7.10

    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git

  test:
    docker:
      - image: circleci/node:7.10
        environment:
          - NODE_ENV: test
          - PGHOST: 127.0.0.1
          - PGUSER: ubuntu

      - image: circleci/postgres:10.4
        environment:
          - POSTGRES_USER: ubuntu
          - POSTGRES_DB: play_test
          - POSTGRES_PASSWORD: ""

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: run tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
